# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Think Data Science
author: "Tsangyao Chen"
copyright: "2026"
logo: ./_static/logo.png
language: en

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_tags: [skip-execution]
  timeout: 300
  allow_errors: true
  stderr_output: show
  output_cache: true

sphinx:
  extra_extensions:
    - sphinx_new_tab_link
    - sphinx.ext.autodoc
    - sphinx_thebe
  config:
    new_tab_link_show_external_link_icon: true  ### default
    new_tab_link_enable_referrer: false         ### adds rel="noreferrer" by default
    html_use_index: true # default is true, but set it explicitly if unsure
    html_domain_indices: true # keeps domain-specific indices on
    thebe_config:
      # selector: ".thebe-interactive" # Only cells with this class
      repository_url: https://github.com/tychen742/dsm # Online location of your book
      repository_branch: main # Which branch of the repository should be used when creating links (optional)
      selector: "div.cell.tag_thebe-interactive"
      selector_input: "div.cell_input"
      selector_output: "div.cell_output"
    html_theme_options:
      repository_url: https://github.com/tychen742/dsm
      repository_branch: main
      # show_prev_next: true
      navigation_with_keys: true
      use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      launch_buttons:
        thebe: true
        binderhub_url: "https://mybinder.org"


# Information about where the book exists on the web
repository:
  url: https://github.com/tychen742/dsm # Online location of your book
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_numbered_headings: true
  number_toc_depth: 3
  favicon: ./_static/favicon-io_gg/favicon.ico

# Bibtex configuration
bibtex_bibfiles:
  - chapters/references.bib

bibtex_reference_style: label

exclude_patterns:
  - ".venv"
  - "assignments"
  - "materials"
  - "otter_files"
  - "temps"
  - "tests"
  - ".ipynb_checkpoints"
  - ".DS_Store"
  - "README.md"
  - "test3.ipynb"
  - "chapters/appendices/x_chap01-on-programming.ipynb"
  - "chapters/09-pandas/project-ecommerce-purchases-questions.ipynb"
  - "chapters/bibliography.md"
  - "images/**/*.ipynb"
