# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  syntax_highlighter: rouge
  input:          GFM

# Permalinks
permalink:        pretty

# Setup

title:            Data Science with Python
description:      'How to think like a data scientist'
url:              https://datasciencepy.tychen.us/
baseurl:          
email:            tchen@mst.edu
feedbackurl:      

author:
  name:           'Tsangyao Chen' 

  url:            https://tychen.us/

github:
  repo:           https://github.com/tychen742/dataSciencePy
  #               Be sure the 'Issues' feature is activated in 'Settings'
# theme:            minima
theme: jekyll-theme-minimal
# theme: jekyll-theme-minima  ## "could not be found" when deployed by Github Pages

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-paginate

minima:
  skin: dark  
